import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "./components/Navbar";
import GlobalCoinMarketDisplay from "./components/GlobalCoinMarketDisplay";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Crypto App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <body className={inter.className}>
          <StoreProvider>
        <GlobalCoinMarketDisplay />
        <div className="px-20">
        <Navbar />
        {children}
        </div>
        </StoreProvider>
        </body>
    </html>
  );
}
