import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import GlobalCoinMarketDisplay from "./components/GlobalCoinMarketDisplay";
import Providers from "../../Providers";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Crypto App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F3F5F9] dark:bg-[#13121A]`}>
        <Providers>
          <GlobalCoinMarketDisplay />
          <Navbar />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
